server:
  port: 8080
  daemon: true
  #host: 192.168.0.241
    
spring:
  application:
    name: smic-server-1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smic?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: appuser
    password: appuser
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: false
    show-sql: true
  hateoas:
    use-hal-as-default-json-media-type: false
  boot:
    admin:
      client:
        url: http://localhost:8090

#springdoc:
#  use-management-port: true
#  show-actuator: true
#  api-docs.path: /swaggerui
#  packagesToScan: com.virnect.smic.server

management:
  server:
    port: 8091
  endpoints:
    web:
      exposure:
        include: "*"
  metrics.tags.application: ${spring.application.name}
  
logging:
  level:
    root: info
    com.virnect.smic.daemon.service.tasklet: info

smic:
  opc-server:
    # host: 35.232.112.205
    # port: 8932
    pool-size: 3
    host: 222.98.122.50
    port: 4850
  kiosk:
    user-id: kiosk1
    password: kiosk1234567890
#    organization-name: %26%23x3164;
    host: 222.98.122.37
    port: 9530
    login-uri: Thingworx/action-login
    plan-uri: Thingworx/Things/EF.OrderMashupQuery.TH/Services/SelectPlanNameToday
    order-uri: Thingworx/Things/EF.OrderMashupManagement.TH/Services/InsertOrder

mq: 
  queue-manager: rabbitmq
  producer-manager: rabbitmq
  kafka:
    enabled: false
    host: 127.0.0.1 #34.123.51.107
    port: 9092
  rabbitmq:
    enabled: true
    host: 127.0.0.1
    port: 5672