server:
  port: 8090
  
spring:
  application:
    name: remote-service-server-local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smic_demon?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: appuser
    password: appuser
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: false
    show-sql: true

logging:
  level:
    root: info
    com.virnect.smic.daemon.service.tasklet: debug
    
opc-server:
#   host: 35.232.112.205
#   port: 8932
  host: 222.98.122.50
  port: 4840

kafka:
  host: 127.0.0.1 #34.123.51.107
  port: 9092

resource:
  tag:
    file:
      - 011-agv-conv.equipment.nodeId.txt
      - 011-agv-conv.supply.nodeId.txt
      - 020-kitting.equipment.nodeId.txt
      - 020-kitting.quality.nodeId.txt
      - 020-kitting.supply.nodeId.txt

my:
  node-id-static:
    - Channel1.Device1._System._Simulated
    - Channel1.Device1._System._SecondsInError
    - Channel1.Device1._System._ScanRateMs
    - Channel1.Device1._System._ScanMode
    - Channel1.Device1._System._NoError
    - Channel1.Device1._System._Error
    - Channel1.Device1._System._Enabled
    - Channel1.Device1._System._DeviceId
    - Channel1.Device1._System._Description
    - Channel1.Device1._System._DemandPoll
    - Channel1.Device1._System._ActiveTagCount
    - Data Type Examples.16 Bit Device._System._Simulated
    - Data Type Examples.16 Bit Device._System._SecondsInError
    - Data Type Examples.16 Bit Device._System._ScanRateMs
    - Data Type Examples.16 Bit Device._System._ScanMode
    - Data Type Examples.16 Bit Device._System._NoError
    - Data Type Examples.16 Bit Device._System._Error
    - Data Type Examples.16 Bit Device._System._Enabled
    - Data Type Examples.16 Bit Device._System._DeviceId
    - Data Type Examples.16 Bit Device._System._Description
    - Data Type Examples.16 Bit Device._System._DemandPoll
    - Data Type Examples.16 Bit Device._System._ActiveTagCount
  node-id-type:
    - Data Type Examples.8 Bit Device.R Registers.WordArray
    - Data Type Examples.8 Bit Device.R Registers.Word4
    - Data Type Examples.8 Bit Device.R Registers.Word3
    - Data Type Examples.8 Bit Device.R Registers.Word2
    - Data Type Examples.8 Bit Device.R Registers.Word1
    - Data Type Examples.8 Bit Device.R Registers.ShortArray
    - Data Type Examples.8 Bit Device.R Registers.Short4
    - Data Type Examples.8 Bit Device.R Registers.Short3
    - Data Type Examples.8 Bit Device.R Registers.Short2
    - Data Type Examples.8 Bit Device.R Registers.Short1
    - Data Type Examples.8 Bit Device.R Registers.QWordArray
    - Data Type Examples.8 Bit Device.R Registers.QWord4
    - Data Type Examples.8 Bit Device.R Registers.QWord3
    - Data Type Examples.8 Bit Device.R Registers.QWord2
    - Data Type Examples.8 Bit Device.R Registers.QWord1
    - Data Type Examples.8 Bit Device.R Registers.LongArray
    - Data Type Examples.8 Bit Device.R Registers.Long4
    - Data Type Examples.8 Bit Device.R Registers.Long3
    - Data Type Examples.8 Bit Device.R Registers.Long2
    - Data Type Examples.8 Bit Device.R Registers.Long1
    - Data Type Examples.8 Bit Device.R Registers.LLongArray
    - Data Type Examples.8 Bit Device.R Registers.LLong4
    - Data Type Examples.8 Bit Device.R Registers.LLong3
    - Data Type Examples.8 Bit Device.R Registers.LLong2
    - Data Type Examples.8 Bit Device.R Registers.LLong1
    - Data Type Examples.8 Bit Device.R Registers.FloatArray
    - Data Type Examples.8 Bit Device.R Registers.Float4
    - Data Type Examples.8 Bit Device.R Registers.Float3
    - Data Type Examples.8 Bit Device.R Registers.Float2
    - Data Type Examples.8 Bit Device.R Registers.Float1
    - Data Type Examples.8 Bit Device.R Registers.DoubleArray
    - Data Type Examples.8 Bit Device.R Registers.Double4
    - Data Type Examples.8 Bit Device.R Registers.Double3
    - Data Type Examples.8 Bit Device.R Registers.Double2
    - Data Type Examples.8 Bit Device.R Registers.Double1
    - Data Type Examples.8 Bit Device.R Registers.DWordArray
    - Data Type Examples.8 Bit Device.R Registers.DWord4
    - Data Type Examples.8 Bit Device.R Registers.DWord3
    - Data Type Examples.8 Bit Device.R Registers.DWord2
    - Data Type Examples.8 Bit Device.R Registers.DWord1
    - Data Type Examples.8 Bit Device.R Registers.CharArray
    - Data Type Examples.8 Bit Device.R Registers.Char4
    - Data Type Examples.8 Bit Device.R Registers.Char3
    - Data Type Examples.8 Bit Device.R Registers.Char2
    - Data Type Examples.8 Bit Device.R Registers.Char1
    - Data Type Examples.8 Bit Device.R Registers.ByteArray
    - Data Type Examples.8 Bit Device.R Registers.Byte4
    - Data Type Examples.8 Bit Device.R Registers.Byte3
    - Data Type Examples.8 Bit Device.R Registers.Byte2
    - Data Type Examples.8 Bit Device.R Registers.Byte1
    - Data Type Examples.8 Bit Device.R Registers.Boolean4
    - Data Type Examples.8 Bit Device.R Registers.Boolean3
    - Data Type Examples.8 Bit Device.R Registers.Boolean2
    - Data Type Examples.8 Bit Device.R Registers.Boolean1
    - Data Type Examples.16 Bit Device.R Registers.WordArray
    - Data Type Examples.16 Bit Device.R Registers.Word4
    - Data Type Examples.16 Bit Device.R Registers.Word3
    - Data Type Examples.16 Bit Device.R Registers.Word2
    - Data Type Examples.16 Bit Device.R Registers.Word1
    - Data Type Examples.16 Bit Device.R Registers.ShortArray
    - Data Type Examples.16 Bit Device.R Registers.Short4
    - Data Type Examples.16 Bit Device.R Registers.Short3
    - Data Type Examples.16 Bit Device.R Registers.Short2
    - Data Type Examples.16 Bit Device.R Registers.Short1
    - Data Type Examples.16 Bit Device.R Registers.QWordArray
    - Data Type Examples.16 Bit Device.R Registers.QWord4
    - Data Type Examples.16 Bit Device.R Registers.QWord3
    - Data Type Examples.16 Bit Device.R Registers.QWord2
    - Data Type Examples.16 Bit Device.R Registers.QWord1
    - Data Type Examples.16 Bit Device.R Registers.LongArray
    - Data Type Examples.16 Bit Device.R Registers.Long4
    - Data Type Examples.16 Bit Device.R Registers.Long3
    - Data Type Examples.16 Bit Device.R Registers.Long2
    - Data Type Examples.16 Bit Device.R Registers.Long1
    - Data Type Examples.16 Bit Device.R Registers.LLongArray
    - Data Type Examples.16 Bit Device.R Registers.LLong4
    - Data Type Examples.16 Bit Device.R Registers.LLong3
    - Data Type Examples.16 Bit Device.R Registers.LLong2
    - Data Type Examples.16 Bit Device.R Registers.LLong1
    - Data Type Examples.16 Bit Device.R Registers.FloatArray
    - Data Type Examples.16 Bit Device.R Registers.Float4
    - Data Type Examples.16 Bit Device.R Registers.Float3
    - Data Type Examples.16 Bit Device.R Registers.Float2
    - Data Type Examples.16 Bit Device.R Registers.Float1
    - Data Type Examples.16 Bit Device.R Registers.DoubleArray
    - Data Type Examples.16 Bit Device.R Registers.Double4
    - Data Type Examples.16 Bit Device.R Registers.Double3
    - Data Type Examples.16 Bit Device.R Registers.Double2
    - Data Type Examples.16 Bit Device.R Registers.Double1
    - Data Type Examples.16 Bit Device.R Registers.DWordArray
    - Data Type Examples.16 Bit Device.R Registers.DWord4
    - Data Type Examples.16 Bit Device.R Registers.DWord3
    - Data Type Examples.16 Bit Device.R Registers.DWord2
    - Data Type Examples.16 Bit Device.R Registers.DWord1
    - Data Type Examples.16 Bit Device.R Registers.Boolean4
    - Data Type Examples.16 Bit Device.R Registers.Boolean3
    - Data Type Examples.16 Bit Device.R Registers.Boolean2
    - Data Type Examples.16 Bit Device.R Registers.Boolean1
  node-id-sim:
    - SimulationExamples.Functions.User4
    - SimulationExamples.Functions.User3
    - SimulationExamples.Functions.User2
    - SimulationExamples.Functions.User1
    - SimulationExamples.Functions.Sine4
    - SimulationExamples.Functions.Sine3
    - SimulationExamples.Functions.Sine2
    - SimulationExamples.Functions.Sine1
    - SimulationExamples.Functions.Random8
    - SimulationExamples.Functions.Random7
    - SimulationExamples.Functions.Random6
    - SimulationExamples.Functions.Random5
    - SimulationExamples.Functions.Random4
    - SimulationExamples.Functions.Random3
    - SimulationExamples.Functions.Random2
    - SimulationExamples.Functions.Random1
    - SimulationExamples.Functions.Ramp8
    - SimulationExamples.Functions.Ramp7
    - SimulationExamples.Functions.Ramp6
    - SimulationExamples.Functions.Ramp5
    - SimulationExamples.Functions.Ramp4
    - SimulationExamples.Functions.Ramp3
    - SimulationExamples.Functions.Ramp2
    - SimulationExamples.Functions.Ramp1
